#pragma once
#include "Platform.h"
enum GameState : uint8
{
	UNKNOWN ,
	GAME_STATE_MAIN_MENU ,
	GAME_STATE_PAUSE ,
	GAME_STATE_STARTING ,
	GAME_STATE_PLAYING ,
	GAME_STATE_GAME_OVER ,
	GAME_STATE_DYING ,
	GAME_STATE_WIN ,
	GAME_STATE_WINNING
};